# Generated by Django 2.2.2 on 2019-06-22 15:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MMSAttachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_sid', models.CharField(max_length=256)),
                ('file', models.FileField(upload_to='mms_attachments')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SentSms',
            fields=[
                ('account_sid', models.CharField(max_length=256)),
                ('sid', models.CharField(max_length=256, primary_key=True, serialize=False)),
                ('from_num', models.CharField(max_length=32)),
                ('to', models.CharField(max_length=32)),
                ('body', models.CharField(max_length=4096)),
                ('status', models.CharField(max_length=16)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'twilio_sms_data',
            },
        ),
        migrations.CreateModel(
            name='AuthenticationParameters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_sid', models.CharField(max_length=256)),
                ('auth_token', models.CharField(max_length=256)),
                ('phone_number', models.CharField(max_length=65)),
                ('sms_password', models.CharField(editable=False, max_length=32)),
                ('rand_identificator', models.CharField(editable=False, max_length=32)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'twilio_auth_params',
            },
        ),
    ]
