# Generated by Django 2.2.2 on 2019-06-23 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('twillioapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='authenticationparameters',
            name='rand_identificator',
        ),
        migrations.RemoveField(
            model_name='authenticationparameters',
            name='sms_password',
        ),
    ]
