# Generated by Django 2.2.2 on 2019-06-29 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twillioapp', '0002_auto_20190623_1936'),
    ]

    operations = [
        migrations.AddField(
            model_name='sentsms',
            name='have_seen',
            field=models.BooleanField(default=False),
        ),
    ]
