# Generated by Django 2.2.3 on 2019-07-14 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twillioapp', '0006_contacts'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacts',
            name='contact_country',
            field=models.CharField(default=0, max_length=32),
            preserve_default=False,
        ),
    ]
