# Generated by Django 2.2.3 on 2019-08-14 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twillioapp', '0007_contacts_contact_country'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlphaNumericCountries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=256)),
                ('code', models.CharField(blank=True, max_length=16, null=True)),
                ('is_alpha', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'twilio_alphanumeric_countries',
            },
        ),
    ]
