# Generated by Django 2.2.3 on 2019-08-29 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twillioapp', '0008_alphanumericcountries'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contacts',
            name='contact_country',
        ),
        migrations.AddField(
            model_name='contacts',
            name='contact_country_code',
            field=models.CharField(default='', max_length=16),
            preserve_default=False,
        ),
    ]
